### PR TITLE
Use nightly binaries and installation shell script from drake

### PR DESCRIPTION
**Pull request by jamiesnape**
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/htmlbook/5)

### CODE REVIEW

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/htmlbook/5)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jamiesnape)

___
*[workflows/ci/bionic/setup, line 21 at r1](https://reviewable.io/reviews/russtedrake/htmlbook/5#-MTp6QNE97-hBQWHOl-Q:-MTp6QNE97-hBQWHOl-R:b7re8jf) ([raw file](https://github.com/russtedrake/htmlbook/blob/8e31db43cf4a717da14a3b3deafb383a5bcad2ff/workflows/ci/bionic/setup#L21)):*
> ```
> popd
> 
> yes | /opt/drake/share/drake/setup/install_prereqs
> ```

We changed this before because I only need the binary requirements for drake, not the from_source requirements.  I think the packages approach is better?

https://github.com/RussTedrake/underactuated/commit/256cb5c9bfbcc9b82bf21cbc45b9f4e5b3a41efb#diff-8c5967fd8486f34493710cc39b240aad46536cf4ee421ffd0479e6542db03e36

and I'm pretty sure you wrote it that way here in the first place:
https://github.com/RussTedrake/underactuated/blame/c3b272bfa2b09557929bb540a4fd759be1fe53d1/scripts/workflows/ci/bionic/setup

**Review by RussTedrake — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/htmlbook/5)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jamiesnape)

___
*[workflows/ci/catalina/setup, line 27 at r1](https://reviewable.io/reviews/russtedrake/htmlbook/5#-MTp7CVgDtclMI8lN3ju:-MTp7CVgDtclMI8lN3jv:b1jet0p) ([raw file](https://github.com/russtedrake/htmlbook/blob/8e31db43cf4a717da14a3b3deafb383a5bcad2ff/workflows/ci/catalina/setup#L27)):*
> ```
> rm -f /usr/local/bin/2to3 # Temporary fix
> 
> /opt/drake/share/drake/setup/install_prereqs
> ```

same comment as above.

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/russtedrake/htmlbook/5)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jamiesnape and @RussTedrake)

___
*[workflows/ci/bionic/setup, line 21 at r1](https://reviewable.io/reviews/russtedrake/htmlbook/5#-MTp6QNE97-hBQWHOl-Q:-MTpLtYl4CEQQsCPZrli:b7682m9) ([raw file](https://github.com/russtedrake/htmlbook/blob/8e31db43cf4a717da14a3b3deafb383a5bcad2ff/workflows/ci/bionic/setup#L21)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

We changed this before because I only need the binary requirements for drake, not the from_source requirements.  I think the packages approach is better?

https://github.com/RussTedrake/underactuated/commit/256cb5c9bfbcc9b82bf21cbc45b9f4e5b3a41efb#diff-8c5967fd8486f34493710cc39b240aad46536cf4ee421ffd0479e6542db03e36

and I'm pretty sure you wrote it that way here in the first place:
https://github.com/RussTedrake/underactuated/blame/c3b272bfa2b09557929bb540a4fd759be1fe53d1/scripts/workflows/ci/bionic/setup
</blockquote></details>

We trimmed that file down since, It will only be the binary dependencies, It is this file: https://github.com/RobotLocomotion/drake/blob/master/setup/ubuntu/binary_distribution/install_prereqs.sh

**Review by RussTedrake — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/russtedrake/htmlbook/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jamiesnape)

___
*[workflows/ci/bionic/setup, line 21 at r1](https://reviewable.io/reviews/russtedrake/htmlbook/5#-MTp6QNE97-hBQWHOl-Q:-MTpOqoCDEZBhyhXIgc0:bb7ohn6) ([raw file](https://github.com/russtedrake/htmlbook/blob/8e31db43cf4a717da14a3b3deafb383a5bcad2ff/workflows/ci/bionic/setup#L21)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

We trimmed that file down since, It will only be the binary dependencies, It is this file: https://github.com/RobotLocomotion/drake/blob/master/setup/ubuntu/binary_distribution/install_prereqs.sh
</blockquote></details>

sgtm

**Pull request merged**
